# Generated by Django 2.2.5 on 2019-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contest', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
